name: smartai
description: SmartAI Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.9
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.2
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  dio: ^5.9.2
  flutter_secure_storage: ^10.3.1
  image_picker: ^1.1.2  # Make sure this is only here ONCE
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/android-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/