# Generated by Django 5.1 on 2026-06-16 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_messages_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_messages_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_speech_minutes_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_speech_minutes_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='translation_chars_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='translation_chars_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
